// This file is automatically generated. Do not edit it directly.
// DISABLED - App uses MongoDB, not Supabase
// import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types';

// const SUPABASE_URL = "https://cgihldwnyxgdymbskypo.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnaWhsZHdueXhnZHltYnNreXBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNzgyOTIsImV4cCI6MjA2MTk1NDI5Mn0.M2kQCcyZFWLjHs5RNqgNYXBT8vd2k8mq2VRbPLvJjYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
export const supabase = null as any;